//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeNight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrunFoto
    {
        public int urunID { get; set; }
        public string urunFoto { get; set; }
    
        public virtual tblUrun tblUrun { get; set; }
    }
}
