//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeNight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUrun()
        {
            this.tblUrunFoto = new HashSet<tblUrunFoto>();
            this.tblKullanici1 = new HashSet<tblKullanici>();
        }
    
        public int urunID { get; set; }
        public int kategoriID { get; set; }
        public int kullaniciID { get; set; }
        public string urunAd { get; set; }
        public string urunAciklama { get; set; }
        public Nullable<double> satildigiKonum { get; set; }
        public System.DateTime satildigiTarih { get; set; }
        public decimal fiyat { get; set; }
        public string fotolink { get; set; }
    
        public virtual tblKategori tblKategori { get; set; }
        public virtual tblKullanici tblKullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUrunFoto> tblUrunFoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKullanici> tblKullanici1 { get; set; }
    }
}
